#!/usr/bin/env python3
"""Build the current bilingual-reference corpus for Japan's 2025 AI Act.

The Japanese e-Gov XML is the controlling source.  The Ministry of Justice
translation is attached as a government-published reference with an explicit
no-legal-effect notice.  No translation is generated by this importer.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from xml.etree import ElementTree as ET

from legal_corpus_utils import content_sha256, snapshot_sha256, write_json


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SNAPSHOT_DIR = ROOT / "data" / "v2" / "source-snapshots"
DEFAULT_OUTPUT = ROOT / "data" / "v2" / "jp-ai-promotion-act-2025-articles.json"
DEFAULT_MANIFEST = ROOT / "data" / "v2" / "jp-ai-promotion-act-2025-corpus-manifest.json"

AS_OF = "2026-07-20"
LAW_ID = "507AC0000000053"
INSTRUMENT_ID = "jp-ai-promotion-act-2025"
CURRENT_REVISION_ID = "507AC0000000053_20250901_000000000000000"

CURRENT_XML_NAME = "jp-ai-promotion-act-507AC0000000053-current-2026-07-20.xml"
REVISIONS_NAME = "jp-ai-promotion-act-507AC0000000053-revisions-2026-07-20.json"
EN_REFERENCE_NAME = "jp-ai-promotion-act-government-en-reference.xml"
EN_HISTORY_NAME = "jp-ai-promotion-act-government-en-reference-history.html"
CAO_STATUS_NAME = "jp-ai-promotion-act-cao-status.html"

CURRENT_SOURCE = (
    "https://laws.e-gov.go.jp/api/2/law_file/xml/"
    f"{LAW_ID}?asof={AS_OF}"
)
CURRENT_PAGE = f"https://laws.e-gov.go.jp/law/{LAW_ID}?occasion_date=20260720"
REVISIONS_SOURCE = f"https://laws.e-gov.go.jp/api/2/law_revisions/{LAW_ID}"
EN_REFERENCE_SOURCE = (
    "https://www.japaneselawtranslation.go.jp/en/laws/download/5066/06/"
    "r07Aa000530105en18.0.xml"
)
EN_REFERENCE_PAGE = (
    "https://www.japaneselawtranslation.go.jp/en/laws/view/5066/en"
)
EN_HISTORY_SOURCE = (
    "https://www.japaneselawtranslation.go.jp/en/laws/history/5066"
)
CAO_STATUS_SOURCE = "https://www8.cao.go.jp/cstp/ai/ai_act/ai_act.html"

STRUCTURE_TAGS = {
    "Part": "part",
    "Chapter": "chapter",
    "Section": "section",
    "Subsection": "subsection",
    "Division": "division",
}


def node_text(element: ET.Element | None, language: str) -> str:
    if element is None:
        return ""
    if language == "ja":
        parts: list[str] = []

        def visit(node: ET.Element) -> None:
            if node.text and node.text.strip():
                parts.append(re.sub(r"\s+", " ", node.text.strip()))
            for child in node:
                visit(child)
                if child.tail and child.tail.strip():
                    parts.append(re.sub(r"\s+", " ", child.tail.strip()))

        visit(element)
        return "".join(parts)
    return re.sub(r"\s+", " ", "".join(element.itertext())).strip()


def element_sha256(element: ET.Element) -> str:
    return content_sha256(ET.tostring(element, encoding="unicode"))


def paragraph_units(paragraph: ET.Element, language: str) -> list[str]:
    head = "".join(
        node_text(child, language)
        for child in paragraph
        if child.tag in {"ParagraphNum", "ParagraphSentence"}
    )
    units = [head] if head else []
    for child in paragraph:
        if child.tag in {"ParagraphNum", "ParagraphSentence"}:
            continue
        text = node_text(child, language)
        if text:
            units.append(text)
    if not units:
        text = node_text(paragraph, language)
        if text:
            units.append(text)
    return units


def article_text(article: ET.Element, language: str) -> tuple[list[str], str]:
    title = node_text(article.find("ArticleTitle"), language)
    caption = node_text(article.find("ArticleCaption"), language)
    paragraphs: list[str] = []
    for paragraph in article.findall("Paragraph"):
        paragraphs.extend(paragraph_units(paragraph, language))
    if not paragraphs:
        raise ValueError(f"Article {article.get('Num')} has no text")
    separator = "　" if language == "ja" else " "
    paragraphs[0] = f"{title}{separator}{paragraphs[0]}".strip()
    full_text = "\n\n".join(([caption] if caption else []) + paragraphs)
    return paragraphs, full_text


def supplementary_text(
    block: ET.Element, language: str, article_limit: int | None = None
) -> tuple[list[str], str, int]:
    label = node_text(block.find("SupplProvisionLabel"), language)
    parts: list[str] = [label]
    article_count = 0
    for child in block:
        if child.tag == "SupplProvisionLabel":
            continue
        if child.tag == "Article":
            if article_limit is not None and article_count >= article_limit:
                break
            _, text = article_text(child, language)
            article_count += 1
        else:
            text = node_text(child, language)
        if text:
            parts.append(text)
    return parts[1:], "\n\n".join(parts), article_count


def iter_articles(
    node: ET.Element, hierarchy: dict[str, dict[str, str]] | None = None
):
    hierarchy = hierarchy or {}
    for child in node:
        if child.tag == "Article":
            yield child, hierarchy
            continue
        hierarchy_key = STRUCTURE_TAGS.get(child.tag)
        if hierarchy_key:
            original_title = node_text(child.find(f"{child.tag}Title"), "ja")
            child_hierarchy = {
                **hierarchy,
                hierarchy_key: {
                    "id": f"jp-ai-promotion-act-2025-{hierarchy_key}-{child.get('Num', '0')}",
                    "label": original_title,
                    "title": original_title,
                    "originalTitle": original_title,
                },
            }
            yield from iter_articles(child, child_hierarchy)
            continue
        yield from iter_articles(child, hierarchy)


def snapshot_entry(
    snapshot_dir: Path,
    filename: str,
    source_url: str,
    media_type: str,
    role: str,
    rights_profile: str,
) -> dict:
    return {
        "path": f"data/v2/source-snapshots/{filename}",
        "sourceUrl": source_url,
        "retrievedOn": AS_OF,
        "mediaType": media_type,
        "role": role,
        "sha256": snapshot_sha256(snapshot_dir / filename),
        "rightsProfile": rights_profile,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--snapshot-dir", type=Path, default=DEFAULT_SNAPSHOT_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args()

    snapshot_dir: Path = args.snapshot_dir
    current_path = snapshot_dir / CURRENT_XML_NAME
    revisions_path = snapshot_dir / REVISIONS_NAME
    en_reference_path = snapshot_dir / EN_REFERENCE_NAME
    en_history_path = snapshot_dir / EN_HISTORY_NAME
    cao_status_path = snapshot_dir / CAO_STATUS_NAME
    for path in (
        current_path,
        revisions_path,
        en_reference_path,
        en_history_path,
        cao_status_path,
    ):
        if not path.exists():
            raise FileNotFoundError(path)

    root = ET.parse(current_path).getroot()
    if root.get("Lang") != "ja" or root.findtext("LawNum") != "令和七年法律第五十三号":
        raise ValueError("Pinned current XML is not the Japanese AI Promotion Act")
    body = root.find("LawBody")
    if body is None or body.findtext("LawTitle") != "人工知能関連技術の研究開発及び活用の推進に関する法律":
        raise ValueError("Unexpected AI Act title")
    main_provision = body.find("MainProvision")
    supplementary = body.find("SupplProvision")
    if main_provision is None or supplementary is None:
        raise ValueError("AI Act main or supplementary provisions are missing")

    revisions = json.loads(revisions_path.read_text(encoding="utf-8"))
    if revisions.get("law_info", {}).get("law_id") != LAW_ID:
        raise ValueError("Revision snapshot has the wrong Law ID")
    revision_rows = revisions.get("revisions", [])
    current_revision = next(
        (row for row in revision_rows if row.get("law_revision_id") == CURRENT_REVISION_ID),
        None,
    )
    if current_revision is None or current_revision.get("current_revision_status") != "CurrentEnforced":
        raise ValueError("The 1 September 2025 AI Act revision is not current and enforced")
    if any(row.get("current_revision_status") == "UnEnforced" for row in revision_rows):
        raise ValueError("Unexpected promulgated future AI Act revision")

    en_root = ET.parse(en_reference_path).getroot()
    en_main = en_root.find("./LawBody/MainProvision")
    en_supplementary = en_root.find("./LawBody/SupplProvision")
    if en_main is None or en_supplementary is None:
        raise ValueError("Government English reference XML is incomplete")
    en_articles = en_main.findall(".//Article")
    en_article_by_number = {article.get("Num"): article for article in en_articles}
    if len(en_articles) != 28 or len(en_article_by_number) != 28:
        raise ValueError("Government English reference lacks the 28 main Articles")
    en_supplement_articles = en_supplementary.findall("Article")
    if len(en_supplement_articles) != 5:
        raise ValueError("Expected five source-original English supplementary article nodes")
    history_text = en_history_path.read_text(encoding="utf-8")
    if "August 22, 2025" not in history_text or "18.0" not in history_text:
        raise ValueError("Government English translation history metadata changed")
    cao_text = cao_status_path.read_text(encoding="utf-8")
    if "全面施行" not in cao_text or "９月１日" not in cao_text:
        raise ValueError("Cabinet Office snapshot does not confirm full commencement")

    japanese_rights = {
        "reuseStatus": "e-gov-secondary-use-unrestricted",
        "license": "e-Gov Law Search reuse statement",
        "licenseUrl": "https://laws.e-gov.go.jp/help",
        "attribution": (
            "Source: e-Gov Law Search, Digital Agency, Government of Japan. "
            "The original Japanese text alone has legal effect."
        ),
    }
    english_rights = {
        "reuseStatus": "public-data-license-1.0",
        "license": "Public Data License (Version 1.0)",
        "licenseUrl": "https://www.japaneselawtranslation.go.jp/en/index/terms",
        "attribution": "Japanese Law Translation Database System, Ministry of Justice, Japan.",
    }
    common_source_version = {
        "lawId": LAW_ID,
        "lawNumber": "令和七年法律第五十三号",
        "promulgatedOn": "2025-06-04",
        "asOf": AS_OF,
        "revisionId": CURRENT_REVISION_ID,
        "fullyEffectiveFrom": "2025-09-01",
        "sourceDocumentSha256": snapshot_sha256(current_path),
        "revisionHistorySha256": snapshot_sha256(revisions_path),
        "competentAuthoritySnapshotSha256": snapshot_sha256(cao_status_path),
        "textState": "current-effective-consolidation",
        "normalization": (
            "XML indentation is removed; statutory characters and source order are "
            "preserved. Captions, paragraphs, and direct list items are separated for display."
        ),
    }
    translation_version = {
        "sourceDocumentSha256": snapshot_sha256(en_reference_path),
        "translationHistorySha256": snapshot_sha256(en_history_path),
        "translatedOn": "2025-08-22",
        "publishedOnDatabase": "2026-01-30",
        "dictionaryVersion": "18.0",
        "currentJapaneseRevisionId": CURRENT_REVISION_ID,
        "versionAlignment": "same-enactment-no-subsequent-amendment",
    }
    authority_note = (
        "Government-published reference from the Japanese Law Translation Database. "
        "That database states that translations are not official texts and have no "
        "legal effect; consult the original Japanese text."
    )

    main_articles = list(iter_articles(main_provision))
    numbers = [article.get("Num") for article, _ in main_articles]
    if numbers != [str(index) for index in range(1, 29)]:
        raise ValueError("AI Act main Articles are not the complete sequence 1..28")

    units: list[dict] = []
    for article, hierarchy in main_articles:
        number = article.get("Num")
        en_article = en_article_by_number[number]
        ja_caption = node_text(article.find("ArticleCaption"), "ja")
        ja_title = node_text(article.find("ArticleTitle"), "ja")
        en_caption = node_text(en_article.find("ArticleCaption"), "en")
        ja_paragraphs, ja_full_text = article_text(article, "ja")
        en_paragraphs, en_full_text = article_text(en_article, "en")
        applies_from = "2025-06-04" if int(number) <= 17 else "2025-09-01"
        unit = {
            "id": f"jp-ai-promotion-act-2025-art-{number}",
            "instrumentId": INSTRUMENT_ID,
            "unitType": "article",
            "articleNumber": number,
            "label": f"Article {number}",
            "originalLabel": ja_title,
            "title": en_caption.strip("()") or f"Article {number}",
            "originalTitle": f"{ja_title}{ja_caption}",
            "chapter": hierarchy.get("chapter"),
            "section": hierarchy.get("section"),
            "subsection": hierarchy.get("subsection"),
            "paragraphs": ja_paragraphs,
            "fullText": ja_full_text,
            "language": "ja-JP",
            "translations": {
                "en": {
                    "title": en_caption.strip("()") or f"Article {number}",
                    "paragraphs": en_paragraphs,
                    "fullText": en_full_text,
                    "language": "en",
                    "status": "government-reference-translation-no-legal-effect",
                    "authorityNote": authority_note,
                    "source": EN_REFERENCE_PAGE,
                    "sourceLabel": "Japanese Law Translation Database — government reference",
                    "sourceXmlPath": f"MainProvision/Article[@Num='{number}']",
                    "sourceNodeSha256": element_sha256(en_article),
                    "sourceVersion": translation_version,
                    "contentSha256": content_sha256(en_full_text),
                    "rights": english_rights,
                }
            },
            "alignment": {
                "level": "article",
                "status": "government-source-number-aligned",
                "originalUnitCount": 28,
                "englishUnitCount": 28,
                "note": "No translation was generated; both government source files use Articles 1 through 28.",
            },
            "textAvailability": "full-japanese-with-current-government-english-reference",
            "legalEffectStatus": "in-force",
            "appliesFrom": applies_from,
            "versionAsOf": AS_OF,
            "source": CURRENT_PAGE,
            "sourceFragment": f"{CURRENT_PAGE}#Mp-At_{number}",
            "sourceLabel": "e-Gov Law Search — current Japanese consolidation",
            "sourceXmlPath": f"MainProvision/Article[@Num='{number}']",
            "retrievedOn": AS_OF,
            "sourceVersion": common_source_version,
            "sourceNodeSha256": element_sha256(article),
            "contentSha256": content_sha256(ja_full_text),
            "rights": japanese_rights,
        }
        for key in ("part", "division"):
            if hierarchy.get(key):
                unit[key] = hierarchy[key]
        units.append(unit)

    ja_supp_paragraphs, ja_supp_full, ja_supp_count = supplementary_text(
        supplementary, "ja"
    )
    en_supp_paragraphs, en_supp_full, en_aligned_count = supplementary_text(
        en_supplementary, "en", article_limit=2
    )
    if ja_supp_count != 2 or en_aligned_count != 2:
        raise ValueError("Current Japanese supplementary Articles 1 and 2 did not align")
    units.append(
        {
            "id": "jp-ai-promotion-act-2025-supplementary-provisions",
            "instrumentId": INSTRUMENT_ID,
            "unitType": "supplementary-provision-block",
            "label": "Supplementary Provisions",
            "originalLabel": "附則",
            "title": "Supplementary Provisions",
            "originalTitle": "附則",
            "paragraphs": ja_supp_paragraphs,
            "fullText": ja_supp_full,
            "language": "ja-JP",
            "translations": {
                "en": {
                    "title": "Supplementary Provisions",
                    "paragraphs": en_supp_paragraphs,
                    "fullText": en_supp_full,
                    "language": "en",
                    "status": "government-reference-translation-no-legal-effect",
                    "authorityNote": authority_note,
                    "source": EN_REFERENCE_PAGE,
                    "sourceLabel": "Japanese Law Translation Database — government reference",
                    "sourceXmlPath": "LawBody/SupplProvision/Article[1..2]",
                    "sourceNodeSha256": element_sha256(en_supplementary),
                    "sourceVersion": translation_version,
                    "contentSha256": content_sha256(en_supp_full),
                    "rights": english_rights,
                }
            },
            "alignment": {
                "level": "current-supplementary-extract",
                "status": "government-current-operative-units-aligned",
                "originalUnitCount": 2,
                "englishAlignedUnitCount": 2,
                "englishSourceOriginalUnitCount": 5,
                "note": (
                    "The current e-Gov extract retains Supplementary Articles 1 and 2. "
                    "The translation source also preserves spent enactment-only amending "
                    "and adjustment provisions; those extra source-original nodes are not "
                    "presented as current Japanese law."
                ),
            },
            "textAvailability": "full-japanese-with-current-government-english-reference",
            "legalEffectStatus": "in-force-current-consolidation",
            "appliesFrom": "2025-06-04",
            "versionAsOf": AS_OF,
            "source": CURRENT_PAGE,
            "sourceFragment": CURRENT_PAGE,
            "sourceLabel": "e-Gov Law Search — current Japanese consolidation",
            "sourceXmlPath": "LawBody/SupplProvision[1]",
            "retrievedOn": AS_OF,
            "sourceVersion": common_source_version,
            "sourceNodeSha256": element_sha256(supplementary),
            "contentSha256": content_sha256(ja_supp_full),
            "rights": japanese_rights,
        }
    )

    snapshots = [
        snapshot_entry(snapshot_dir, CURRENT_XML_NAME, CURRENT_SOURCE, "application/xml", "current-effective-text", "egov"),
        snapshot_entry(snapshot_dir, REVISIONS_NAME, REVISIONS_SOURCE, "application/json", "revision-history", "egov"),
        snapshot_entry(snapshot_dir, EN_REFERENCE_NAME, EN_REFERENCE_SOURCE, "application/xml", "current-government-reference-translation", "jlt-pdl-1.0"),
        snapshot_entry(snapshot_dir, EN_HISTORY_NAME, EN_HISTORY_SOURCE, "text/html", "translation-version-history", "jlt-pdl-1.0"),
        snapshot_entry(snapshot_dir, CAO_STATUS_NAME, CAO_STATUS_SOURCE, "text/html", "competent-authority-commencement-status", "audit-only"),
    ]
    manifest = {
        "instrumentId": INSTRUMENT_ID,
        "lawId": LAW_ID,
        "officialTitle": "人工知能関連技術の研究開発及び活用の推進に関する法律",
        "englishReferenceTitle": (
            "Act on Promotion of Research and Development, and Utilization of "
            "Artificial Intelligence-related Technology"
        ),
        "retrievedOn": AS_OF,
        "hashAlgorithm": "SHA-256",
        "currentVersion": {
            "asOf": AS_OF,
            "revisionId": CURRENT_REVISION_ID,
            "promulgatedOn": "2025-06-04",
            "partlyEffectiveFrom": "2025-06-04",
            "fullyEffectiveFrom": "2025-09-01",
            "status": "current-fully-in-force",
            "futureRevisionTextIncluded": False,
            "promulgatedFutureRevisionCount": 0,
        },
        "corpus": {
            "path": "data/v2/jp-ai-promotion-act-2025-articles.json",
            "nodeCount": len(units),
            "mainArticleCount": len(main_articles),
            "currentSupplementaryArticleCount": ja_supp_count,
            "supplementaryProvisionBlockCount": 1,
            "contentSha256": content_sha256(
                "\n\n".join(unit["fullText"] for unit in units)
            ),
        },
        "promulgatedFutureRevisions": [],
        "translation": {
            "language": "en",
            "status": "government-published-reference-current-no-legal-effect",
            "source": EN_REFERENCE_PAGE,
            "translatedOn": "2025-08-22",
            "publishedOnDatabase": "2026-01-30",
            "dictionaryVersion": "18.0",
            "mainArticleCount": len(en_articles),
            "currentSupplementaryArticleCountAligned": en_aligned_count,
            "sourceOriginalSupplementaryArticleNodeCount": len(en_supplement_articles),
            "versionDifference": (
                "No later amendment exists. The English source translates the original "
                "enactment and preserves spent supplementary amendment provisions that the "
                "current e-Gov extract omits; current corpus alignment therefore uses the 28 "
                "main Articles and current Supplementary Articles 1 and 2 only."
            ),
            "legalEffect": authority_note,
        },
        "rights": {
            "primaryJapaneseText": japanese_rights,
            "referenceTranslation": english_rights,
        },
        "sourceSnapshots": snapshots,
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_json(args.output, units)
    write_json(args.manifest, manifest)
    print(
        f"Wrote {len(units)} AI Act nodes: {len(main_articles)} main Articles and "
        f"one current Supplementary Provisions block ({ja_supp_count} Articles)"
    )


if __name__ == "__main__":
    main()
